<a href="https://colab.research.google.com/github/muk-e-ni/Python-DSA/blob/main/Graph.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [75]:
from collections import deque # to reduce time complexity of the queue
import numpy as np

class Graph:
  def __init__(self, directed = False):
    self.directed = directed
    self.adj_list = dict()

  def __repr__(self):
    graph_string = ""
    for v, adj in self.adj_list.items():
      graph_string += f"{v}:> {adj}\n"
    return graph_string

  def add_vertex(self, vertex):
    if vertex not in self.adj_list:
      self.adj_list[vertex] = set()

    else:
      raise ValueError(f"Vertex {vertex} already in graph")

  def remove_vertex(self, vertex):
    if vertex not in self.adj_list:
      raise ValueError(f"Vertex {vertex} not in graph")

    else:
      for neighbours in self.adj_list.values():
        if vertex in neighbours:
          neighbours.remove(vertex)

      del self.adj_list[vertex]
  def add_edge(self, v1, v2, weight=None):
    if v1 not in self.adj_list:
      self.add_vertex(v1)

    if v2 not in self.adj_list:
      self.add_vertex(v2)

    if weight is None:
      self.adj_list[v1].add9(v2)
      if not self.directed:
        self.adj_list[v2].add(v1)

    else:
      self.adj_list[v1].add((v2, weight))
      if not self.directed:
        self.adj_list[v2].add((v1, weight))
  def remove_edge(self,v1, v2):
    if v1 not in self.adj_list or v2 not in self.adj_list:
      raise ValueError('Edge does not exist')

    for neighbour in list(self.adj_list[v1]):
      if isinstance(neighbour, tuple):
        if neighbour[0] == v2:
          self.adj_list[v1].remove(neighbour)
          break
      else:
        if neighbour == v2:
          self.adj_list[v1].remove(neighbour)
    if not self.directed:
      for neighbour in self.adj_list[v2]:
        if isinstance(neighbour, tuple):
          if neighbour[0] == v1:
           self.adj_list[v2].remove(neighbour)
           break

        else:
          if neighbour == v1:
            self.adj_list[v2].remove(neighbour)
    else:
      raise ValueError('Edge does not exist')

  def get_neighbours(self, v):
    if v not in self.adj_list:
      raise ValueError(f"Vertex {v} not in graph")

    else:
      return self.adj_list.get(v, set())
  def get_vertexes(self):
    return list(self.adj_list.keys())
  def has_vertex(self, v):
    return v in self.adj_list

  def has_edge(self, v1, v2):
    if v1 not in self.adj_list:
      return False

    for neighbour in self.adj_list[v1]:
      if isinstance(v2, tuple):
        if neighbour[0] == v2:
          return True
      else:
        if neighbour[0] == v2:
          return True
      return False

  def get_edges(self):
    edges = []
    for v1, neighbours in self.adj_list.items():
      for v2 in neighbours:
        edges.append((v1, v2))
    return edges

  # uses queue data structure

  def bfs(self, start):
    visited_vertexes = set()
    queue = deque([start])
    order = []

    while queue:
      vertex = queue.popleft()
      if vertex not in visited_vertexes:
        visited_vertexes.add(vertex)
        order.append(vertex)
        neighbours = self.get_neighbours(vertex)
        for neighbour in neighbours:
          if isinstance(neighbour, tuple):
            neighbour = neighbour[0]
          if neighbour not in visited_vertexes:
              queue.append(neighbour)
    return order

  # uses stack data structure
  def dfs(self, start):
    visited_vertexes = set()
    stack = [start]
    order = []

    while stack:
      vertex = stack.pop()
      if vertex not in visited_vertexes:
        visited_vertexes.add(vertex)
        order.append(vertex)
        neighbours = self.get_neighbours(vertex)
        for neighbour in neighbours:
          if isinstance(neighbour, tuple):
            neighbour = neighbour[0]
          if neighbour not in visited_vertexes:
            stack.append(neighbour)
    return order
  def to_adj_matrix(self):
    vertexes = self.get_vertexes()
    index = {vertex: i for i, vertex in enumerate(vertexes)}
    matrix = [[0 for _ in range(len(vertexes))] for _ in range(len(vertexes))]
    for v1, neighbours in self.adj_list.items():
      for v2 in neighbours:
        if isinstance(v2, tuple):
          to, weight = v2
          matrix[index[v1]][index[to]] = weight
        else:
          matrix[index[v1]][index[v2]] = 1
    return matrix, vertexes





In [78]:
if __name__ == "__main__":
  g = Graph()

  g.add_edge('A', 'B', 1)
  g.add_edge('A', 'C', 2)
  g.add_edge('B', 'C', 3)
  g.add_edge('B', 'D',10)
  g.add_edge('C', 'D', 4)
  g.add_edge('D', 'E', 1)
  g.add_edge('E', 'F', 1)
  g.add_edge('F', 'G', 1)
  g.add_edge('G', 'F', 1)
  g.add_edge('G', 'E', 1)
  g.add_edge('G', 'D', 1)

  print("adjacency list: \n", g, end="\n\n")
  print("adjacency matrix: \n", np.array(g.to_adj_matrix()[0]), end="\n\n")

  import numpy as np

  print ("BFS from A: ",g.bfs('A'))
  print ("DFS from A: ", g.dfs('A'))





adjacency list: 
 A:> {('B', 1), ('C', 2)}
B:> {('D', 10), ('A', 1), ('C', 3)}
C:> {('B', 3), ('D', 4), ('A', 2)}
D:> {('E', 1), ('C', 4), ('B', 10), ('G', 1)}
E:> {('F', 1), ('G', 1), ('D', 1)}
F:> {('E', 1), ('G', 1)}
G:> {('F', 1), ('E', 1), ('D', 1)}


adjacency matrix: 
 [[ 0  1  2  0  0  0  0]
 [ 1  0  3 10  0  0  0]
 [ 2  3  0  4  0  0  0]
 [ 0 10  4  0  1  0  1]
 [ 0  0  0  1  0  1  1]
 [ 0  0  0  0  1  0  1]
 [ 0  0  0  1  1  1  0]]

BFS from A:  ['A', 'B', 'C', 'D', 'E', 'G', 'F']
DFS from A:  ['A', 'C', 'D', 'G', 'E', 'F', 'B']


In [79]:
print("Has Edge A to B? \n", g.has_edge('A', 'B'), end= '\n\n')
print("Has Edge A to E? \n", g.has_edge('A', 'E'), end= '\n\n')
print("Get Neighbours of A: \n", g.get_neighbours('A'), end='\n\n')
print("Get all Vertexes: \n", g.get_vertexes(), end='\n\n')
print("Has Vertex A? \n", g.has_vertex('A'), end='\n\n')
print("Has Vertex H? \n", g.has_vertex('H'), end='\n\n')
print("Get Edges: \n", g.get_edges(), end='\n\n')
print("Remove Edge A to B: \n")
g.remove_edge('A', 'B')
print(g, end='\n\n')



Has Edge A to B? 
 True

Has Edge A to E? 
 False

Get Neighbours of A: 
 {('B', 1), ('C', 2)}

Get all Vertexes: 
 ['A', 'B', 'C', 'D', 'E', 'F', 'G']

Has Vertex A? 
 True

Has Vertex H? 
 False

Get Edges: 
 [('A', ('B', 1)), ('A', ('C', 2)), ('B', ('D', 10)), ('B', ('A', 1)), ('B', ('C', 3)), ('C', ('B', 3)), ('C', ('D', 4)), ('C', ('A', 2)), ('D', ('E', 1)), ('D', ('C', 4)), ('D', ('B', 10)), ('D', ('G', 1)), ('E', ('F', 1)), ('E', ('G', 1)), ('E', ('D', 1)), ('F', ('E', 1)), ('F', ('G', 1)), ('G', ('F', 1)), ('G', ('E', 1)), ('G', ('D', 1))]

Remove Edge A to B: 

A:> {('C', 2)}
B:> {('D', 10), ('C', 3)}
C:> {('B', 3), ('D', 4), ('A', 2)}
D:> {('E', 1), ('C', 4), ('B', 10), ('G', 1)}
E:> {('F', 1), ('G', 1), ('D', 1)}
F:> {('E', 1), ('G', 1)}
G:> {('F', 1), ('E', 1), ('D', 1)}


